version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - "9005:9000"